function [v_scat, max_abs_change] = obl_plane_wave_scat_soft(k, a, theta0, path, xi1, x, y, z)
	[ ...
	v_scat, max_abs_change ...
	] = obl_calculate_sum(k, a, path, x, y, z, @(k, a, c, m, n, everything, eta, xi, phi)(calculate_plane_wave_scat_term(k, a, c, m, n, everything, eta, xi, phi, theta0, xi1, 'soft')));
end
