function [v_scat, max_abs_change] = obl_point_source_scat_hard(k, a, eta0, xi0, path, xi1, x, y, z)
	[ ...
	v_scat, max_abs_change ...
	] = obl_calculate_sum(k, a, path, x, y, z, @(k, a, c, m, n, everything, eta, xi, phi)(calculate_point_source_scat_term(k, a, c, m, n, everything, eta, xi, phi, eta0, xi0, xi1, 'hard')));
end
