function generate_obl_plane_wave_in_figure(k, a, theta0, w, nels)
	[ ...
	x, y, z ...
	] = create_slice([-w; 0.0; w], [0.0; 0.0; -2.0 * w], [2.0 * w; 0.0; 0.0], nels, nels);
	x = reshape(x, 1, nels * nels);
	y = reshape(y, 1, nels * nels);
	z = reshape(z, 1, nels * nels);
	[ ...
	v_in, grad_in_cart ...
	] = plane_wave_in(k, sin(theta0), 0.0, cos(theta0), x, y, z);
	[ ...
	v_scat, grad_scat_cart, max_abs_change_scat ...
	] = obl_plane_wave_in(k, a, theta0, 'saved', x, y, z);
	v_in = reshape(v_in, nels, nels);
	v_scat = reshape(v_scat, nels, nels);
	
	cool_plot([-w, w], [-w, w], 'x (m)', 'z (m)', '', log10(abs(v_scat - v_in)), 0.0, [-6.0, 0.0], cubehelix(250), 0.0, 0.0);
end
