function [change, max_abs_change] = calculate_plane_wave_scat_term(k, a, c, m, n, everything, eta, xi, phi, theta0, xi1, imped)
	if (m == 0)
		epsilon = 1.0;
	else
		epsilon = 2.0;
	end
	if (strcmp(imped, 'soft'))
		temp = interp1(everything.R.xi, everything.R.R1, xi1, 'spline') / interp1(everything.R.xi, everything.R.R1 + 1i * everything.R.R2, xi1, 'spline');
	else
		temp = interp1(everything.R.xi, everything.R.R1p, xi1, 'spline') / interp1(everything.R.xi, everything.R.R1p + 1i * everything.R.R2p, xi1, 'spline');
	end
	change = ...
	-2.0 * ...
	epsilon * ...
	(1i ^ n) * ...
	interp1(everything.S1.eta, everything.S1.S1, cos(theta0), 'spline') * ...
	temp * ...
	interp1(everything.S1.eta, everything.S1.S1, eta, 'spline') .* ...
	interp1(everything.R.xi, everything.R.R1 + 1i * everything.R.R2, xi, 'spline') .* ...
	cos(m * phi);
	max_abs_change = max(abs(change(xi >= xi1)));
end
