function [change, max_abs_change] = calculate_plane_wave_in_term(k, a, c, m, n, everything, eta, xi, phi, theta0)
	if (m == 0)
		epsilon = 1.0;
	else
		epsilon = 2.0;
	end
	change = ...
	2.0 * ...
	epsilon * ...
	(1i ^ n) * ...
	interp1(everything.S1.eta, everything.S1.S1, cos(theta0), 'spline') * ...
	interp1(everything.S1.eta, everything.S1.S1, eta, 'spline') .* ...
	interp1(everything.R.xi, everything.R.R1, xi, 'spline') .* ...
	cos(m * phi);
	max_abs_change = max(abs(change));
end
